name: Refresh containers in Portainer

on:
  workflow_run:
    workflows: ["Beta autodeploy action", "Stable autodeploy action"]
    types: [completed]

jobs:
  successful-build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Get latest commit hash
      id: fetch-latest-hash
      run: echo "::set-output name=latest-hash::$(git rev-parse --short $GITHUB_SHA)"

    - name: Fetch latest release version
      id: fetch-latest-release
      uses: reloc8/action-latest-release-version@1.0.0

    - name: Deploy stack to Portainer
      uses: DaniFoldi/portainer-stack-deploy@v1.3.1
      with:
        portainer-host: ${{ secrets.PORTAINER_HOST }}
        username: ${{ secrets.PORTAINER_USERNAME }}
        password: ${{ secrets.PORTAINER_KEY }}
        endpoint-id: ${{ secrets.PORTAINER_ENDPOINT }}
        stack-name: <STACK_NAME>
        stack-definition: docker-compose.yml
        variables: '{"stable": "${{ steps.fetch-latest-release.outputs.latest-release }}", "beta": "${{ steps.fetch-latest-hash.outputs.latest-hash }}"}'